services:

    planetary-annihilation:
      image: ghcr.io/obiwantoby/pa-dedicated-server:latest
      container_name: pa-dedicated
      restart: unless-stopped
      network_mode: host
      volumes:
        - <yourlocaldir>:/home/steam/PlanetaryAnnihilation-dedicated/
        - steamcmd_login_volume:/home/steam/Steam
      environment:
        - STEAMUSER=yoursteamusername
        - PA_SERVERNAME=pa-server
        - PA_PW=serverpassword

# Reuse your volume that stores your steamcmd login , pleaes cache this first.
volumes:
  steamcmd_login_volume:
    external: true
